### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by wangodanny** [ItsWendell/google-assistant-desktop-client#1]
I need some help as I can't get this to run. My computer is saying can't find directory when I install dependencies. I don't know what to do now
![google](https://user-images.githubusercontent.com/32901175/35780523-75f4e2cc-09d4-11e8-8be9-1c9330c8c390.PNG)

**Comment by ItsWendell** [comment]
@wangodanny Seems like you're not in the right folder, you need to properly clone this repo into it's own folder. Create your own client_secret.json and place it in the right folder as described in the readme;

```
Follow the steps on this page; https://developers.google.com/assistant/sdk/guides/library/python/embed/config-dev-project-and-account

After you've got your client_secret_.json file rename it to client_secret.json and put it in the src/renderer folder. 
```
Once you've done that you should go back to the main folder and run `npm install` there. 

In your current situation it looks like you just opened your command-line, you need to navigate using 
for example 'cd c:\your\project\folder' and run the command described.
