### ISSUE TITLE
Electron Rebuild Failure?

### ISSUE THREAD

**Issue by ghost** [ItsWendell/google-assistant-desktop-client#16]
When I try to run `npm install --target=2.0.0 --runtime=electron`, I get an error that the rebuild failed.

Full output is at the pastebin: https://pastebin.com/tNtimehX

**Comment by ItsWendell** [comment]
Thanks for your interest in this project! I just updated the readme and some packages, could you try again by pulling the latest version?

Instead of doing `npm install --target=2.0.0 --runtime=electron` you should just be able to do `npm install` !

**Comment by ghost** [comment]
That got it to work!

I'm getting a screen now saying my OAuth2 isn't set up. Looking through the instructions, it kinda glazes over that part. What exactly do I need to enable there?

**Comment by ghost** [comment]
Got the OAuth fixed, will open another issue with an error I'm facing
