### ISSUE TITLE
Can you apply a deb or appimage package？

### ISSUE THREAD

**Issue by sikenali** [ItsWendell/google-assistant-desktop-client#2]

**Comment by ItsWendell** [comment]
@jingle0927 Can you further explain?

**Comment by sikenali** [comment]
Yes
I  am deepin user

**Comment by ItsWendell** [comment]
@jingle0927 As a Deepin OS user, are you missing an app image?

**Comment by sikenali** [comment]
There is no such application under Linux, and community users have also needs.
