### ISSUE TITLE
Getting error when attempting to run

### ISSUE THREAD

**Issue by tankerkiller125** [ItsWendell/google-assistant-desktop-client#3]
I am using Elementary OS and when I attempt to run this project I get the following error:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at registerTrayIcon (/home/matthew/PhpstormProjects/google-assistant-desktop-client/dist/electron/main.js:2592:13)
    at App.createWindow (/home/matthew/PhpstormProjects/google-assistant-desktop-client/dist/electron/main.js:2612:2)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
```

I have the client_secret.json in the correct directory and everything. The only thing I changed was that I removed the --target from the npm install command because it kept giving me a 404 error when attempting to get the robotjs dependency.

Is their any solution to this?

**Comment by tankerkiller125** [comment]
Ok, so an update. I was able to fix that issue by adding an else if statement for linux. However I still have an issue where grpc will not compile. I added the target and runtime options back in but I still can not get it to install no matter what I try.

**Comment by tankerkiller125** [comment]
Ok so I found a really odd solution but it works. I installed electron-rebuild with the runtime and target info (which detected grpc and worked perfectly) and then I installed the electron-builder again (with the runtime and target info) and then finally the normal npm install (with target and runtime options). This worked perfectly even though it was by far a very very weird work around.

**Comment by ItsWendell** [comment]
@tankerkiller125 Feel free to shoot in an PR request for the icon fix on Elemetery OS! I'll look into natively building GRPC properly, you could try to use yarn instead of NPM, I heard it handles native libraries a bit better.

**Comment by tankerkiller125** [comment]
@WMisiedjan I'll try yarn next time, and a shoot your a PR for the icon.
