### ISSUE TITLE
Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

### ISSUE THREAD

**Issue by piccinnigius** [ItsWendell/google-assistant-desktop-client#6]
Hi, i searched to fix that issue editing '.editorconfig' and /test/.eslintrc files but doesn't work.
I'm working under windows 10, any help? 
Thank you

**Comment by ItsWendell** [comment]
@piccinnigius I see that you solved this yourself? Care to share what happened and how you solved this?

**Comment by piccinnigius** [comment]
@WMisiedjan  Yeah, i solved with command:

`npm run lint -- --fix`

when i try to build or run dev i get this error:

> Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style

then: `npm run lint -- --fix` fixed this errors

**Comment by ItsWendell** [comment]
Nice I'll keep track too see if this issue happens more often, I'm on Windows 10 too, I don't have the issue but I know it might be something to do with git converting the files

**Comment by piccinnigius** [comment]
@WMisiedjan i've again issued this error and finally found the origin and fixed.
This issue happen when you **clone the git** and can be fixed by downloading the .zip file from Github instead of cloning or on cloned repo you can:

1. open with Notepad++  `.src\main\index.js`

1.  go to edit>EOL Conversion > Unix (LF) > Save

PS. If in the build log see other similars errors on other files do the same thing
